name: Publish to GHCR

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  publish-to-ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/Mathieu2301/Miakamera:latest
        docker push ghcr.io/Mathieu2301/Miakamera:latest
